# Generated by Django 4.0.4 on 2022-05-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('publishAt', models.DateTimeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
